<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>seabot2_screen_driver</name>
  <version>1.0.0</version>
  <description>Driver to the screen of seabot2</description>
  <maintainer email="thomas.le_mezo@ensta-bretagne.org">Thomas Le Mézo</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>pressure_bme280_driver</build_depend>
  <build_depend>pressure_ms5803_driver</build_depend>
  <build_depend>seabot2_power_driver</build_depend>
  <build_depend>seabot2_mission</build_depend>
  <build_depend>seabot2_power_driver</build_depend>
  <build_depend>seabot2_safety</build_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>pressure_bme280_driver</exec_depend>
  <exec_depend>pressure_ms5803_driver</exec_depend>
  <exec_depend>seabot2_mission</exec_depend>
  <exec_depend>seabot2_power_driver</exec_depend>
  <exec_depend>seabot2_safety</exec_depend>


  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>