driver:
  pressure_ms5803_node:
    ros__parameters:
      enable: false

  pressure_ms5837_node:
    ros__parameters:
      enable: true

  thruster_node:
    ros__parameters:
      reverse_angular_velocity: true
      reverse_left: false
      reverse_right: true

  temperature_node:
    ros__parameters:
      i2c_address: 0x77

  audio_recorder_node:
    ros__parameters:
      frequency_middle: 35000
      frequency_range: 5000
      robot_code_: 2