driver:
  pressure_ms5803_node:
    ros__parameters:
      enable: false

  pressure_ms5837_node:
    ros__parameters:
      enable: true

  thruster_node:
    ros__parameters:
      reverse_angular_velocity: true
      reverse_left: true
      reverse_right: false

  temperature_node:
    ros__parameters:
      i2c_address: 0x77

  audio_recorder:
    ros__parameters:
      robot_code: 5